# Catena template catalog.
#
# Two things are hand-edited: sources/<id>.json and the compose in
# blueprints/<id>/. Everything else is generated by `make render` and
# drift-gated in CI, so the only workflow that ever needs to change is:
# edit the input, run `make`, commit the diff.

.DEFAULT_GOAL := all
.PHONY: all render validate lint test verify serve image clean

## all: validate, render, lint, test -- the pre-commit pass
all: render lint test

## render: per-blueprint README + logo + quiesce, templates.json, catalog.json, index.html
render:
	uv run build/render.py

## validate: schema-check the inputs and the committed templates.json, write nothing
validate:
	uv run build/validate.py

## lint: unattended-hook security lint + Postgres pins + swarm compatibility
lint:
	uv run build/lint_quiesce.py
	uv run build/lint_postgres_pins.py
	uv run build/lint_swarm.py

## test: unit tests over the build library
test:
	uv run --with pytest --with jsonschema --with pyyaml pytest tests/ -q

## verify: what CI runs -- render must be idempotent against the commit
verify: render
	git diff --exit-code blueprints templates.json catalog.json index.html

## serve: preview the generated catalog locally on :8000
serve:
	python3 -m http.server 8000

## image: build the nginx image that serves the catalog from this tree
image:
	docker build -t catena-templates:local .

## clean: drop the generated root artifacts (they are committed; this is for bisecting).
## blueprints/ is spared: it holds the hand-edited compose files.
clean:
	rm -f templates.json catalog.json index.html
